Financial circuit readme upgrades
ConsenSysMesh/EnterpriseZK pull request #9
Opened 2023-01-24 20:22 UTC by Ybittan

2023-01-31 19:53 UTC, Kasshern commented on financial-circuit-service/README.md
> +**Note**: Currenty the circuit does not support number of years input greater than 18. There is potential for future upgrades if the need is found.
Currently

2023-01-31 19:58 UTC, Kasshern requested changes
One spelling mistake and one sentence that seems kinda confusing that I commented on.

2023-01-31 19:58 UTC, Kasshern commented on financial-circuit-service/README.md
> +The ZK circuit takes in the 4 necessary values for calculating the future value (Future Value, Present Value, Interest Rate, and Number of years). The circuit will then prove that the user correctly
"Anyone can then take that proof and proving key, and provide it to the prover function along with the other public values (Interest Rate and Number of Years) and the proving key, and cryptographically prove the correctness of the end value, without needing the private future and present values. "   This sentence seems to mention proving key twice. Also I think at this point in the flow they are providing this information to the verifying function?

2023-02-06 15:19 UTC, markymark-26 approved these changes
lgtm

2023-02-06 15:19 UTC, markymark-26 commented
@GoldenBit0 pls review

2023-02-07 20:22 UTC, Kasshern approved these changes

2023-02-07 20:22 UTC, merged